version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - devgalopnetwork
    volumes:
      - mongodbstorage:/data/db
  
  mydotnetapp:
    image: mydotnetapp:development
    build:
      context: ../
      dockerfile: ./Dockerfile
    env_file:
      - ./development.env
    volumes:
      - myappstorage:/input
    networks:
      - devgalopnetwork
    ports:
      - "5300:5500"
    depends_on:
      - mongodb

volumes:
  mongodbstorage:
  myappstorage:

networks:
  devgalopnetwork:
    driver: bridge